name: CI - Task Manager

on:
  push:
    branches: [ developpement, main ]
  pull_request:
    branches: [ developpement, main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
      - name: Cloner le repo
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage pylint

      - name: Lancer pylint
        run: |
          pylint src/ || true  # pour ne pas bloquer le job si note < 10

      - name: Lancer les tests
        run: |
          python -m coverage run -m unittest discover tests
          python -m coverage report

      - name: Générer les artefacts de couverture
        run: coverage html

      - name: Sauvegarder les artefacts (rapport HTML)
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: htmlcov
