name: Génération de la documentation

on:
  push:
    branches:
      - developpement
      - main
  pull_request:

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install sphinx

      - name: Générer la documentation HTML
        run: |
          sphinx-build -b html docs/source docs/build/html

      - name: Upload de la documentation générée
        uses: actions/upload-artifact@v4
        with:
          name: documentation-html
          path: docs/build/html
